import Foundation
import CoreGraphics

enum Form { case chair, chest, table, bureau, mirror, clock, stool, cabinet, coffer, box }
enum Leg { case turned, cabriole, square, bracket, bun, sabre, none, ball }

struct PieceSpec {
    let slug: String
    let name: String
    let period: String
    let year: Int
    let region: String
    let timber: Tone
    let timberName: String
    let form: Form
    let leg: Leg
    let drawers: Int
    let panels: Int
    let width: Double
    let height: Double
    let moulding: Int
    let hardware: String
    let line: String
    let evidence: [(String, String)]
}

let pieceBook: [PieceSpec] = pieceA + pieceB + pieceC + pieceD

let pieceA: [PieceSpec] = [
    PieceSpec(slug: "oakcoffer", name: "Oak Coffer", period: "Jacobean", year: 1650,
              region: "West Country", timber: Field.oak, timberName: "English oak",
              form: .coffer, leg: .none, drawers: 0, panels: 3, width: 1.0, height: 0.52,
              moulding: 2, hardware: "Wrought iron strap hinges",
              line: "Riven oak, pegged frame and panel, and three centuries of wax",
              evidence: [("Riven, not sawn", "The boards were split along the grain with a froe, so the surface follows the medullary rays and no saw mark appears anywhere on it."),
                         ("Pegged mortice and tenon", "Every joint is drawbored: the peg hole in the tenon is offset so driving the peg pulls the shoulder tight. Nothing is glued."),
                         ("Iron, not brass", "Strap hinges hand forged, with hammer marks still on the face and nail holes punched rather than drilled."),
                         ("Shrinkage across the grain", "The panels have shrunk in width and the original paint line shows at the edges. They float in their grooves, which is why nothing has split.")]),
    PieceSpec(slug: "wainscot", name: "Wainscot Chair", period: "Charles II", year: 1670,
              region: "Yorkshire", timber: Field.oak.dk(0.06), timberName: "English oak",
              form: .chair, leg: .turned, drawers: 0, panels: 1, width: 0.62, height: 1.0,
              moulding: 1, hardware: "None",
              line: "A panelled back, a plank seat and legs turned on a pole lathe",
              evidence: [("Pole lathe turning", "The rings are slightly uneven and the tool left a series of fine chatter marks that no powered lathe produces."),
                         ("Carved by hand", "The lunette carving runs out of register at one end because it was set out by eye and cut with a gouge."),
                         ("Seat wear", "The plank seat is worn hollow toward the front edge and along the arms where hands have gripped for centuries."),
                         ("No screws anywhere", "Everything is pegged. A screw in a joint of this date is a repair, and there are two.")]),
    PieceSpec(slug: "walnutchest", name: "Walnut Chest of Drawers", period: "William and Mary", year: 1695,
              region: "London", timber: Field.walnut, timberName: "Walnut veneer on pine",
              form: .chest, leg: .bun, drawers: 4, panels: 0, width: 1.0, height: 0.86,
              moulding: 3, hardware: "Brass drop handles",
              line: "Oyster veneer, half round mouldings and bun feet",
              evidence: [("Veneer laid on pine", "Saw cut veneer nearly two millimetres thick, laid with animal glue. Modern veneer is a tenth of that."),
                         ("Half round moulding", "The moulding runs around the drawer opening on the carcase, not on the drawer front. After about 1710 it moves to the drawer."),
                         ("Drop handles", "Cast brass drops on wire, with the original holes only. A later handle leaves two extra holes inside the drawer."),
                         ("Drawer bottoms front to back", "The boards of the drawer bottom run front to back and are nailed. Side to side and grooved is a later habit.")]),
    PieceSpec(slug: "gatelegtable", name: "Gateleg Table", period: "Late Stuart", year: 1700,
              region: "East Anglia", timber: Field.oak.lt(0.06), timberName: "Oak with elm top",
              form: .table, leg: .turned, drawers: 1, panels: 0, width: 1.0, height: 0.74,
              moulding: 1, hardware: "Iron pivots",
              line: "Bobbin turned, and it folds flat against the wall",
              evidence: [("Bobbin turning", "The pattern repeats but never exactly. Measure two legs and they differ by a millimetre or two in every bead."),
                         ("Wear at the gate", "Where the gate swings, the stretcher is worn to a shallow dish and the pivot hole is oval, not round."),
                         ("Oval top", "The top has shrunk across the grain by nearly ten millimetres, so a top made round now measures oval."),
                         ("Rule joint or butt", "An early gateleg has a plain butt joint at the leaf. The rule joint arrives later and reads as a machine curve.")]),
    PieceSpec(slug: "queenannechair", name: "Queen Anne Side Chair", period: "Queen Anne", year: 1715,
              region: "London", timber: Field.walnut.lt(0.04), timberName: "Walnut",
              form: .chair, leg: .cabriole, drawers: 0, panels: 1, width: 0.60, height: 1.0,
              moulding: 1, hardware: "None",
              line: "A cabriole leg, a vase splat and no stretcher at all",
              evidence: [("The cabriole", "Cut from a solid block and shaped with rasp and file. Look inside the knee for the flat where the block was gripped in the vice."),
                         ("Vase shaped splat", "Sawn from one board, and the grain runs through the whole curve. A modern copy has short grain at the neck and cracks there."),
                         ("No stretchers", "The moment furniture is strong enough to lose its stretchers is a date in itself. Before about 1710 they are still there."),
                         ("Seat rail joints", "Mortice and tenon, pinned, with the glue line dark and shrunken. The rails have shrunk away from the corner blocks.")]),
    PieceSpec(slug: "bureau", name: "Walnut Bureau", period: "George I", year: 1725,
              region: "London", timber: Field.walnut, timberName: "Walnut on oak",
              form: .bureau, leg: .bracket, drawers: 4, panels: 0, width: 1.0, height: 0.96,
              moulding: 2, hardware: "Brass swan neck handles",
              line: "A fall front on lopers, four graduated drawers, bracket feet",
              evidence: [("Graduated drawers", "Each drawer is deeper than the one above by a consistent step. A copy usually gets the rhythm slightly wrong."),
                         ("Hand cut dovetails", "Three per corner, narrow pins, and the marking gauge line runs across the whole board and does not stop."),
                         ("Loper wear", "The lopers that carry the fall are worn to a taper and their housings are polished bright at the top."),
                         ("Oak linings", "Drawer sides of straight grained oak, about ten millimetres, planed and left from the plane. Feel the ripple.")]),
    PieceSpec(slug: "longcase", name: "Longcase Clock", period: "George II", year: 1745,
              region: "Lancashire", timber: Field.oak.dk(0.04), timberName: "Oak with mahogany crossbanding",
              form: .clock, leg: .bracket, drawers: 0, panels: 1, width: 0.42, height: 1.0,
              moulding: 3, hardware: "Brass dial and hinges",
              line: "Eight day movement, brass dial, and a case made locally to fit it",
              evidence: [("Case and movement differ", "Provincial cases were made by a joiner to fit a movement bought in. The two are often a decade apart in style."),
                         ("Hood door lock", "A wooden turn button, not a lock. Locks on hood doors are a nineteenth century habit."),
                         ("Trunk door shrinkage", "The door has shrunk across its width and the beading now stands proud at one edge by two millimetres."),
                         ("Seat board wear", "The board the movement stands on is compressed under the pillars, and the marks match this movement and no other.")]),
    PieceSpec(slug: "chippendale", name: "Mahogany Side Chair", period: "Chippendale", year: 1765,
              region: "London", timber: Field.mahogany, timberName: "Cuban mahogany",
              form: .chair, leg: .square, drawers: 0, panels: 1, width: 0.62, height: 1.0,
              moulding: 2, hardware: "None",
              line: "A pierced splat, square chamfered legs and a slip seat",
              evidence: [("Pierced splat", "Fretted with a bow saw from the back, so the saw kerf breaks out slightly on the front face and was cleaned with a file."),
                         ("Chamfered inner edge", "The inside of each leg is chamfered to lighten it. The chamfer stops short of the stretcher and the stop is cut by hand."),
                         ("Slip seat frame", "Beech, numbered with a chisel to match its chair. Roman numerals cut with a firmer, not written."),
                         ("Cuban mahogany", "Dense, dark, and it rings when tapped. The pores are fine and filled with two centuries of wax.")]),
]

let pieceB: [PieceSpec] = [
    PieceSpec(slug: "peartable", name: "Pembroke Table", period: "George III", year: 1780,
              region: "London", timber: Field.mahogany.lt(0.06), timberName: "Mahogany with satinwood banding",
              form: .table, leg: .square, drawers: 1, panels: 0, width: 1.0, height: 0.76,
              moulding: 1, hardware: "Brass knob",
              line: "Two small flaps on wooden hinges and a single frieze drawer",
              evidence: [("Rule joint", "The flap meets the top in a rule joint, hinged with a knuckle hinge let flush into the underside."),
                         ("Crossbanding", "A band of satinwood laid around the top, mitred at the corners, with a fine boxwood stringing inside it."),
                         ("Drawer runner wear", "The runners are worn to a dished channel with a shoulder at the back where the drawer stopped for two centuries."),
                         ("Fly bracket", "The bracket that swings out to carry the flap is a hand cut knuckle joint. Count the knuckles.")]),
    PieceSpec(slug: "windsor", name: "Windsor Chair", period: "George III", year: 1790,
              region: "Buckinghamshire", timber: Field.elm, timberName: "Elm seat, ash bow, beech legs",
              form: .chair, leg: .turned, drawers: 0, panels: 0, width: 0.66, height: 1.0,
              moulding: 0, hardware: "None",
              line: "Three timbers, no glue in the legs, and a seat adzed from a slab of elm",
              evidence: [("Three woods on purpose", "Elm for the seat because it does not split, ash for the bow because it bends, beech for the legs because it turns."),
                         ("Adzed seat", "The saddle is cut with an adze and a travisher, and the tool marks are still there under the wax if you rake a light across it."),
                         ("Wedged through tenons", "The legs go right through the seat and are wedged from above. The wedge and the leg are different woods."),
                         ("Dry joints", "The legs were driven in green and shrank tight. There is no glue anywhere in the undercarriage.")]),
    PieceSpec(slug: "hepplewhite", name: "Shield Back Chair", period: "Hepplewhite", year: 1795,
              region: "London", timber: Field.mahogany.lt(0.04), timberName: "Mahogany",
              form: .chair, leg: .square, drawers: 0, panels: 1, width: 0.60, height: 1.0,
              moulding: 1, hardware: "None",
              line: "A shield back, tapered legs and spade feet",
              evidence: [("Shield back", "Built up from several pieces with the grain running round the curve. One piece would have short grain and would break."),
                         ("Tapered leg", "The taper is on the two inner faces only. Look at the outside corner: it is dead straight from seat to floor."),
                         ("Spade foot", "A separate block glued and pinned on. Later reproductions carve it from the leg and the grain gives them away."),
                         ("Stuffed over seat", "The rails are rebated for webbing and the original tack holes run in a dense line along the top edge.")]),
    PieceSpec(slug: "sheraton", name: "Sheraton Sideboard", period: "Sheraton", year: 1800,
              region: "London", timber: Field.mahogany, timberName: "Mahogany with boxwood stringing",
              form: .cabinet, leg: .square, drawers: 3, panels: 2, width: 1.0, height: 0.84,
              moulding: 2, hardware: "Brass lion mask ring handles",
              line: "A bow front, six tapered legs and a cellaret drawer lined in lead",
              evidence: [("Bow front construction", "The front is built from laminated pine bricks, veneered over. Tap it and it sounds hollow and even."),
                         ("Boxwood stringing", "A one millimetre line of boxwood let into a scratched groove. The corners are mitred and slightly open with age."),
                         ("Lead lined drawer", "The deep drawer is lined with sheet lead, folded at the corners and tacked. That lining dates the fashion precisely."),
                         ("Original handles", "Lion mask rings, cast and chased. The backplate has worn the surface around it into a bright halo.")]),
    PieceSpec(slug: "regencytable", name: "Regency Sofa Table", period: "Regency", year: 1815,
              region: "London", timber: Field.mahogany.dk(0.04), timberName: "Rosewood veneer",
              form: .table, leg: .sabre, drawers: 2, panels: 0, width: 1.0, height: 0.74,
              moulding: 1, hardware: "Brass lion paw castors",
              line: "Sabre legs, brass paw castors and a top that folds at both ends",
              evidence: [("Sabre legs", "Sawn from a thick plank with the grain following the curve, then finished with a spokeshave."),
                         ("Brass castors", "Lion paw castors with the maker's name stamped in the collar. The leather wheels have worn oval."),
                         ("Rosewood veneer", "Laid in book matched pairs so the figure mirrors across the centre line of the top."),
                         ("Screws in the top", "Hand filed slots, off centre, and the threads run out before the point. Machine screws arrive in the 1850s.")]),
    PieceSpec(slug: "victorianchest", name: "Mahogany Chest", period: "Early Victorian", year: 1845,
              region: "Midlands", timber: Field.mahogany.lt(0.02), timberName: "Mahogany on pine",
              form: .chest, leg: .bracket, drawers: 4, panels: 0, width: 1.0, height: 0.90,
              moulding: 2, hardware: "Turned wooden knobs",
              line: "Straight fronted, wooden knobs, and the first circular saw marks",
              evidence: [("Circular saw marks", "Arcs across the back boards. The circular saw is in general use from about 1830 and there is no going back."),
                         ("Wooden knobs", "Turned mahogany knobs on a screw thread. They replace brass in the 1830s and are back out of fashion by 1870."),
                         ("Machine cut veneer", "Thin, even, and cut on a knife rather than a saw. Under a glass the surface shows no saw ripple at all."),
                         ("Drawer bottoms grooved", "The bottom boards run side to side and sit in a groove, with a muntin down the middle of the wider drawers.")]),
    PieceSpec(slug: "davenport", name: "Davenport Desk", period: "Victorian", year: 1865,
              region: "Lancashire", timber: Field.walnut.lt(0.06), timberName: "Burr walnut",
              form: .bureau, leg: .bun, drawers: 4, panels: 1, width: 0.72, height: 0.94,
              moulding: 3, hardware: "Brass gallery and knobs",
              line: "A sloping leather top, drawers down one side and dummies down the other",
              evidence: [("Burr veneer", "Cut from a burr and laid in quarters. The figure meets at the centre line and the joint is barely visible."),
                         ("Machine dovetails", "Even pins and tails of exactly the same width, and the gauge line stops where the machine stopped."),
                         ("Leather skiver", "A thin leather writing surface, gold tooled at the edge, and the tooling is a wheel run rather than separate stamps."),
                         ("Pop up gallery", "A spring loaded stationery compartment. The mechanism is stamped steel, not hand made.")]),
    PieceSpec(slug: "arts", name: "Arts and Crafts Settle", period: "Arts and Crafts", year: 1900,
              region: "Cotswolds", timber: Field.oak.dk(0.02), timberName: "Quartered English oak",
              form: .chair, leg: .square, drawers: 0, panels: 3, width: 1.0, height: 1.0,
              moulding: 0, hardware: "Wrought iron hinges",
              line: "Everything showing: exposed tenons, chamfers and hand cut pegs",
              evidence: [("Exposed tenons", "Through tenons wedged from outside and left proud, because the joint is meant to be seen and admired."),
                         ("Deliberate tool marks", "The chamfers are cut with a drawknife and not sanded out. That is a decision, not carelessness."),
                         ("Quartered oak", "Sawn through the radius so the medullary rays show as silver flecks across the whole surface."),
                         ("Rose head nails", "Hand forged nails used decoratively on the ironwork, with the hammer facets still sharp.")]),
]

let pieceC: [PieceSpec] = [
    PieceSpec(slug: "boxstool", name: "Box Stool", period: "Commonwealth", year: 1655,
              region: "Welsh borders", timber: Field.oak.dk(0.08), timberName: "Oak",
              form: .stool, leg: .turned, drawers: 0, panels: 2, width: 0.62, height: 0.54,
              moulding: 1, hardware: "Iron hinge",
              line: "A joint stool with a lid, and everything about it is pegged",
              evidence: [("Drawbored pegs", "Look at the peg ends: they are not round but slightly oval, because the offset hole dragged them as they were driven."),
                         ("Scribed lines", "The layout scribe lines are still visible on the rails, and they run past the joint because nobody bothered to clean them off."),
                         ("Foot wear", "The feet have worn away by twenty millimetres, unevenly, and the wear matches a floor that sloped."),
                         ("Original colour", "Under the lid, where light and wax never reached, the oak is the pale honey it started as.")]),
    PieceSpec(slug: "spicebox", name: "Spice Box", period: "Restoration", year: 1680,
              region: "Pennsylvania", timber: Field.walnut.lt(0.02), timberName: "Black walnut",
              form: .box, leg: .bracket, drawers: 6, panels: 1, width: 0.72, height: 0.72,
              moulding: 2, hardware: "Iron lock and brass drops",
              line: "A little cabinet of drawers, locked, because spice was worth locking up",
              evidence: [("Tiny dovetails", "Four to a corner on a drawer forty millimetres deep, cut with a knife rather than a saw at the shoulder."),
                         ("Original lock", "A wrought iron lock let into the door with a hand cut mortice. The key is worn to a shine on one face."),
                         ("Secret drawer", "There is one behind the central bank, released by a wooden spring. Every spice box has one and none advertise it."),
                         ("Interior colour", "The inside of the drawers is bare walnut, oxidised to a warm brown that no stain reproduces.")]),
    PieceSpec(slug: "cornercupboard", name: "Corner Cupboard", period: "George II", year: 1750,
              region: "Shropshire", timber: Field.oak.lt(0.02), timberName: "Oak with mahogany banding",
              form: .cabinet, leg: .none, drawers: 0, panels: 2, width: 0.86, height: 1.0,
              moulding: 3, hardware: "Brass H hinges",
              line: "Hung in a corner, shaped shelves inside, and never meant to be moved",
              evidence: [("H hinges", "Brass H hinges surface mounted, with hand filed screw slots that all point in different directions."),
                         ("Shaped shelves", "The shelves have a shaped front edge with a spoon groove cut along the back. Both are cut by hand and vary."),
                         ("Backboards", "Riven oak, nailed with rose head nails, and the gaps between them have opened by five millimetres with age."),
                         ("No finish inside", "The interior is bare wood. Polishing the inside of a cupboard is a modern idea.")]),
    PieceSpec(slug: "teatable", name: "Tripod Tea Table", period: "George III", year: 1770,
              region: "London", timber: Field.mahogany.dk(0.02), timberName: "Mahogany",
              form: .table, leg: .cabriole, drawers: 0, panels: 0, width: 0.66, height: 0.72,
              moulding: 2, hardware: "Brass birdcage catch",
              line: "A dished top on a birdcage, and it tilts up against the wall",
              evidence: [("Dished top", "Turned from one board with the dish and the rim cut in a single operation on a great wheel lathe."),
                         ("Birdcage", "Four small pillars between two plates, letting the top both tilt and turn. The wedge that locks it is original."),
                         ("Three legs dovetailed", "Each leg is dovetailed into the column and the joint is covered by an iron spider underneath."),
                         ("Shrinkage to oval", "A top turned round in 1770 now measures four millimetres less across the grain than along it.")]),
    PieceSpec(slug: "washstand", name: "Washstand", period: "Regency", year: 1810,
              region: "Provincial", timber: Field.pine.dk(0.10), timberName: "Painted pine",
              form: .table, leg: .turned, drawers: 1, panels: 0, width: 0.70, height: 0.88,
              moulding: 1, hardware: "Turned knob",
              line: "Painted pine, a hole for the bowl, and a splashback",
              evidence: [("Original paint", "Under the later coats there is a thin, hard, slightly translucent paint with visible brush drag. Milk paint, not emulsion."),
                         ("Cut nails", "Rectangular in section, tapering on two sides only. In use from about 1800 to 1890 and then gone."),
                         ("Pine and softwood", "The whole thing is deal, because it was always going to be painted. Nobody wasted mahogany on a washstand."),
                         ("Water damage", "The top has swollen and the joints opened around the bowl hole. That damage is honest and it dates itself.")]),
    PieceSpec(slug: "chiffonier", name: "Chiffonier", period: "William IV", year: 1832,
              region: "London", timber: Field.mahogany, timberName: "Mahogany",
              form: .cabinet, leg: .none, drawers: 1, panels: 2, width: 1.0, height: 0.92,
              moulding: 3, hardware: "Brass grille and knobs",
              line: "Heavy mouldings, brass grilles backed with silk, and a shelf above",
              evidence: [("Heavy scroll moulding", "Run with a moulding plane in several passes. Look for the small step where the plane was reset."),
                         ("Brass grille", "Woven brass wire, backed with pleated silk that has rotted to threads. The original tacks are still there."),
                         ("Saw marks change", "Pit saw marks on the older secondary timber, circular saw on the later repairs. Both are on the same piece."),
                         ("Turned feet", "Squat turned feet, and the wear on them is on the front pair only because it always stood against a wall.")]),
    PieceSpec(slug: "gothicdesk", name: "Gothic Revival Desk", period: "Victorian", year: 1855,
              region: "London", timber: Field.oak.dk(0.06), timberName: "Oak",
              form: .bureau, leg: .square, drawers: 3, panels: 2, width: 1.0, height: 0.92,
              moulding: 3, hardware: "Iron strap hinges and brass",
              line: "Pointed arches, chamfered stops and a great deal of conviction",
              evidence: [("Machine moulding", "The chamfer stops are identical on every member. A hand cut stop never is."),
                         ("Circular saw everywhere", "Every secondary surface carries the arc of a circular saw, including inside the drawers."),
                         ("Machine made screws", "Gimlet points, even threads, and the slot dead centre. That combination means after 1850."),
                         ("Deliberate medievalism", "Iron strap hinges on a piece that does not need them, made in a factory to look forged.")]),
    PieceSpec(slug: "bentwood", name: "Bentwood Chair", period: "Late Victorian", year: 1885,
              region: "Vienna", timber: Field.beech.dk(0.06), timberName: "Steam bent beech",
              form: .chair, leg: .turned, drawers: 0, panels: 0, width: 0.58, height: 1.0,
              moulding: 0, hardware: "Machine screws",
              line: "Six pieces, ten screws, and a million of them made",
              evidence: [("Steamed and bent", "One length of beech steamed and bent round a former. There is no joint anywhere in the back."),
                         ("Machine screws", "Identical, machine made, and they are what holds the whole chair together. It packs flat."),
                         ("Factory stamp", "A paper label or a branded mark under the seat, with a model number. Nothing before this period is numbered."),
                         ("Cane seat", "Hand woven cane in a machine cut groove. The groove is even; the weaving is not.")]),
]

let pieceD: [PieceSpec] = [
    PieceSpec(slug: "creamware", name: "Dressing Mirror", period: "George III", year: 1785,
              region: "London", timber: Field.mahogany.lt(0.08), timberName: "Mahogany and satinwood",
              form: .mirror, leg: .bracket, drawers: 3, panels: 0, width: 0.72, height: 1.0,
              moulding: 2, hardware: "Brass knobs",
              line: "A swing frame on a serpentine box of three small drawers",
              evidence: [("Mercury glass", "The plate is thin, slightly grey, and the silvering has crazed into a fine web at the edges."),
                         ("Bevel by hand", "The bevel is shallow, uneven in width, and it does not run quite parallel to the edge."),
                         ("Serpentine front", "Sawn from the solid and shaped with a compass plane, so the curve is fair but not mathematically true."),
                         ("Original glue blocks", "Small triangular blocks rubbed into the corners with hot glue, shrunken and dark, with no nails.")]),
    PieceSpec(slug: "canterbury", name: "Canterbury", period: "Regency", year: 1820,
              region: "London", timber: Field.mahogany.dk(0.06), timberName: "Rosewood",
              form: .cabinet, leg: .turned, drawers: 1, panels: 0, width: 0.66, height: 0.66,
              moulding: 1, hardware: "Brass castors",
              line: "Four divisions for sheet music, a drawer below and castors on everything",
              evidence: [("Turned spindles", "Every spindle is slightly different in length because each was fitted to its own hole."),
                         ("Rosewood grain", "Dark stripes on a red brown ground, and it smells faintly of roses when freshly cut. It is not a stain."),
                         ("Original castors", "Brass cup castors with the maker stamped on the collar and leather wheels worn flat on one side."),
                         ("Drawer stops", "Small blocks glued to the rails, worn to a shine, and one of them has been replaced.")]),
    PieceSpec(slug: "whatnot", name: "Whatnot", period: "Victorian", year: 1850,
              region: "London", timber: Field.walnut.lt(0.04), timberName: "Walnut",
              form: .cabinet, leg: .turned, drawers: 0, panels: 0, width: 0.60, height: 1.0,
              moulding: 1, hardware: "Brass castors",
              line: "Four graduated tiers on turned supports, for displaying things",
              evidence: [("Machine turning", "The supports are identical to a tenth of a millimetre, which means a copying lathe."),
                         ("Fretwork gallery", "Cut with a treadle fretsaw. The kerf is even, and there are no file marks cleaning it up."),
                         ("Screwed from below", "Each tier is screwed up through the support from underneath. Earlier work would be tenoned."),
                         ("Dust patterns", "A century of dust has darkened the timber everywhere except where objects stood, and those ghosts are still readable.")]),
    PieceSpec(slug: "kitchentable", name: "Scrubbed Pine Table", period: "Victorian", year: 1870,
              region: "Provincial", timber: Field.pine, timberName: "Deal",
              form: .table, leg: .square, drawers: 1, panels: 0, width: 1.0, height: 0.76,
              moulding: 0, hardware: "Iron nails",
              line: "Never polished, scrubbed every week for a hundred years",
              evidence: [("Scrubbed surface", "The soft summer growth has worn away faster than the hard winter rings, so the top has a corduroy ripple."),
                         ("Bleached by soda", "Scrubbing with soda has bleached the top to a pale grey while the underside is still the colour of new pine."),
                         ("Cut nails in the frame", "Rectangular cut nails, and the holes are square. Wire nails, which are round, arrive in the 1890s."),
                         ("Knife scars", "The top carries chopping marks concentrated at one end, where the light from the window fell.")]),
    PieceSpec(slug: "stickstand", name: "Hall Stick Stand", period: "Late Victorian", year: 1890,
              region: "Birmingham", timber: Field.oak.lt(0.04), timberName: "Oak",
              form: .cabinet, leg: .none, drawers: 0, panels: 1, width: 0.50, height: 1.0,
              moulding: 2, hardware: "Cast iron drip tray",
              line: "Cast iron, pressed brass and a great deal of Victorian confidence",
              evidence: [("Cast iron tray", "Sand cast, with the mould parting line still visible along the rim and a casting number underneath."),
                         ("Pressed brass", "Thin brass pressed in a die rather than chased by hand. The relief is even and slightly soft."),
                         ("Machine cut mortices", "Square cornered, all identical, and the cutter left a fine ridge at the bottom of each."),
                         ("Wire nails", "Round in section with a flat head. They date the piece to after about 1890 and nothing earlier.")]),
    PieceSpec(slug: "deco", name: "Art Deco Cocktail Cabinet", period: "Art Deco", year: 1932,
              region: "London", timber: Field.satinwood.dk(0.10), timberName: "Birds eye maple veneer",
              form: .cabinet, leg: .square, drawers: 1, panels: 2, width: 0.86, height: 1.0,
              moulding: 0, hardware: "Chromed steel",
              line: "Stepped, veneered, chrome handled and entirely of its decade",
              evidence: [("Plywood carcase", "Multi ply, machine made, with a paper thin knife cut veneer laid on both faces to balance it."),
                         ("Chrome, not brass", "Electroplated chromium on steel. It pits rather than tarnishes and the pitting is the giveaway."),
                         ("Cellulose finish", "Sprayed cellulose lacquer, which crazes into a fine crackle. Shellac, which is older, does not do that."),
                         ("Machine everything", "Not one hand cut joint anywhere in the piece, and that is a statement rather than an economy.")]),
    PieceSpec(slug: "utility", name: "Utility Sideboard", period: "Utility", year: 1944,
              region: "England", timber: Field.oak.lt(0.08), timberName: "Oak on plywood",
              form: .cabinet, leg: .square, drawers: 2, panels: 2, width: 1.0, height: 0.80,
              moulding: 0, hardware: "Turned wooden handles",
              line: "Made to a government specification, and stamped to prove it",
              evidence: [("The utility mark", "Two stylised cheeses and a number, branded into the back or stamped in ink. It is a legal mark, not a maker's."),
                         ("No ornament at all", "Timber was rationed. Every moulding, every bead and every unnecessary cut was forbidden by regulation."),
                         ("Plywood back", "Nailed on with wire nails, and the plywood is thin and slightly warped with damp."),
                         ("Honest joints", "The joinery is good because it was specified to be. Utility furniture was cheap but it was never shoddy.")]),
    PieceSpec(slug: "ercol", name: "Stacking Chair", period: "Mid Century", year: 1958,
              region: "High Wycombe", timber: Field.beech, timberName: "Beech and elm",
              form: .chair, leg: .turned, drawers: 0, panels: 0, width: 0.58, height: 1.0,
              moulding: 0, hardware: "None",
              line: "A Windsor chair redrawn for a smaller room and a lighter house",
              evidence: [("Steam bent bow", "One piece of beech, steamed and bent, with the compression marks still visible on the inside of the curve."),
                         ("Elm seat", "Machine saddled, so the dish is perfectly even. A hand adzed seat never is."),
                         ("Stacking geometry", "The legs splay to exactly the angle that lets one chair sit inside another. That is a design decision, not tradition."),
                         ("Factory finish", "A thin clear lacquer applied in a booth. There is no wax build up in the corners because there never was any wax.")]),
]
